--GOAL: Is to create a role for customized access and an user to use this role for performing operations.

-- STEP 1: Use an admin role
USE ROLE ACCOUNTADMIN;

-- STEP 2: Create the transform role and assign it to ACCOUNTADMIN

CREATE ROLE IF NOT EXISTS TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

-- STEP 3: Create a default warehouse

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

-- STEP 4: Create the 'dbt' user and assign to the transform role
CREATE USER IF NOT EXISTS dbt
    PASSWORD = 'dbtpass123'
    LOGIN_NAME = 'dbt'
    MUST_CHANGE_PASSWORD = FALSE
    DEFAULT_WAREHOUSE = 'COMPUTE_WH'
    DEFAULT_ROLE = TRANSFORM
    DEFAULT_NAMESPACE = 'NETFLIXANALYSIS.RAW'
    COMMENT = 'dbt user used for data transformation';
ALTER USER dbt SET TYPE = LEGACY_SERVICE;
GRANT ROLE TRANSFORM TO USER dbt;


-- STEP 5: Create a database and schema for the Netflix project
CREATE DATABASE IF NOT EXISTS NETFLIX;
CREATE SCHEMA IF NOT EXISTS NETFLIX.RAW;

-- STEP 6: Grant permissions to the transform role
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
GRANT ALL ON DATABASE NETFLIX TO ROLE TRANSFORM;
GRANT ALL ON ALL SCHEMAS IN DATABASE NETFLIX TO ROLE TRANSFORM;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE NETFLIX TO ROLE TRANSFORM;
GRANT ALL ON ALL TABLES IN SCHEMA NETFLIX.RAW TO ROLE TRANSFORM;
GRANT ALL ON FUTURE TABLES IN SCHEMA NETFLIX.RAW TO ROLE TRANSFORM;